### PR TITLE
Add ability to publish a html changelog from git history

### PR DESCRIPTION
**Pull request by kamaradclimber**
This could be use to generate a changelog and enrich it with the major/risky information.

### CODE REVIEW

**Comment by kamaradclimber** [comment]
cc @aboten @criteo/sre-core

**Comment by pierrecdn** [comment]
OPT: Update the README to precise that you also match 'risky' to colorize html output, independently from a version change.

**Comment by pierrecdn** [comment]
LGTM except from that !

**Comment by kamaradclimber** [comment]
done, thanks for the review

**Pull request merged**
